baseURL: https://blog.arsho.dev/
title: Blog
pagination:
  pagerSize: 5
theme: archie

buildDrafts: true
buildFuture: false
buildExpired: false
enableRobotsTXT: true

permalinks:
  posts: /posts/:year/:slug

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Blog
  description: Personal blog
  subtitle: "\U0001F44B Webエンジニアです"

  social:
    - name: GitHub
      icon: github
      url: https://github.com/sho918
    - name: RSS
      icon: rss
      url: https://blog.arsho.dev/index.xml

menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - name: Tags
      url: tags/
      weight: 10
    - name: Search
      url: search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
